### PR TITLE
spi: spi-cadence: Add support for Slave mode

### PR DESCRIPTION
**Pull request by ghost**
Currently SPI Cadence controller works only in Master mode.
Updated interrupt handler for Full duplex transfer in Slave mode.
Interrupt handler rely on the TX empty interrupt even for Slave mode
transfer due to below HW limitation.

HW limitation:
AR 65885 - SPI Controller Might Not Update RX_NEMPTY Flag, Showing
Incorrect Status Of The Receive FIFO

SPI Slave mode works in the following manner:
1.	One transfer can be finished only after all transfer->len
data been transferred to master device.
2.	Slave device only accepts transfer->len data. Any data longer
than this from master device will be dropped. Any data shorter than
this from master will cause SPI to be stuck due to the above behavior.
3.	The stale data present in RXFIFO will be dropped in unprepared
hardware transfer function.

Signed-off-by: Srinivas Goud <srinivas.goud@amd.com>

Link: https://lore.kernel.org/all/1681825625-10265-3-git-send-email-srinivas.goud@amd.com/
State: upstream (b1b9051)

[https://github.com/Digilent/linux-digilent/commit/48dbbe728e7485b0ab59164a422c2f5f08d607a1]

### CODE REVIEW

**Comment by fukiame** [comment]
there is also no clear benefits in merging these PRs, and they are not even checked for whether they even build or not.

**Comment by fukiame** [comment]
also, commit authorship is non-existent.

**Comment by fukiame** [comment]
please learn Git.

**Comment by ghost** [comment]
oh sir

**Pull request closed without merging**
